# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/site"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler"
    directory: "/site"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/plugin"
    schedule:
      interval: "weekly"
