version: 2
updates:
- package-ecosystem: bundler
  directory: "/site"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: html-proofer
    versions:
    - 3.19.0
- package-ecosystem: npm
  directory: "/site"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: feather-icons
    versions:
    - "< 4.10, >= 4.9.a"
  - dependency-name: feather-icons
    versions:
    - ">= 4.19.a, < 4.20"
  - dependency-name: feather-icons
    versions:
    - "> 4.21.0"
  - dependency-name: feather-icons
    versions:
    - "< 4.9, >= 4.8.a"
