# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Groundhog
email: groundhog@philipbelesky.com
description: a Grasshopper plugin and wiki exploring the applications of computational design in landscape architecture.
version: 0.13.0b

# Build settings
markdown: Pandoc
plugins:
  - jekyll-pandoc
  - jekyll-sitemap # Part of html-proofer tests
pandoc:
  extensions:
    - csl: "./assets/style.csl"
    - bibliography: "./assets/cites.bib"

permalink: pretty # Ditch the .html suffix for links

sass:
  sass_dir: assets

# Custom types
collections:
  documentation:
    output: true
    permalink: /documentation/:title/
    scope:
      path: ""
      type: documentation
  projects:
    output: true
    permalink: /projects/:title/
    scope:
      path: ""
      type: projects
  techniques:
    output: true
    permalink: /techniques/:title/
    scope:
      path: ""
      type: techniques

defaults:
  - scope:
      path: ""
      type: documentation
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      path: ""
      layout: post
  - scope:
      path: ""
      type: techniques
    values:
      layout: post

# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# node_modules not excluded because the font is referenced from there
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .ruby-version
  - package.json
  - package-lock.json
  - s3_website.yml
  - gulpfile.js
  - compile.sh
  - style.csl
  - npm-debug.log
  - vendor # Exclude gem file on travis
  - assets/resize_cache
  - assets/documentation/**/*.jpg # Made by gulp
  - assets/documentation/**/*.jpeg # Made by gulp
  - assets/documentation/**/*.png # Made by gulp
  - assets/projects/**/*.jpg # Made by gulp
  - assets/projects/**/*.jpeg # Made by gulp
  - assets/projects/**/*.png # Made by gulp
  - assets/techniques/**/*.jpg # Made by gulp
  - assets/techniques/**/*.jpeg # Made by gulp
  - assets/techniques/**/*.png # Made by gulp
keep_files:
  - "assets/img" # Made by gulp
