# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Groundhog
email: groundhog@philipbelesky.com
description: is a Grasshopper plugin, a set of reference models, and wiki exploring the applications of computational design in landscape architecture.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://groundhog.la" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
livereload: true
markdown: Pandoc
plugins:
  - jekyll-feed
  - jekyll-pandoc
  - jekyll-sitemap
  - jekyll-tidy
pandoc:
  extensions:
    - csl: "./assets/style.csl"
    - bibliography: "./assets/cites.bib"

google_analytics: UA-314178-30

# Configuration
permalink: pretty # Ditch the .html
sass:
  sass_dir: assets
  style: compressed

# Custom types
collections:
  documentation:
    output: true
    permalink: /documentation/:title/
    scope:
      path: ""
      type: documentation
  projects:
    output: true
    permalink: /projects/:title/
    scope:
      path: ""
      type: projects
  techniques:
    output: true
    permalink: /techniques/:title/
    scope:
      path: ""
      type: techniques

defaults:
  - scope:
      path: ""
      type: documentation
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      path: ""
      layout: post
  - scope:
      path: ""
      type: techniques
    values:
      layout: post

jekyll_tidy:
  # exclude: ["index.html"]
  compress_html: false
  ignore_env: false

# Jekyll-Assets management
assets:
  sources:
    - assets/documentation
    - assets/plugin
    - assets/projects
    - assets/techniques

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - node_modules
  - package.json
  - package-lock.json
  - s3_website.yml
  - compile.sh
  - style.csl
  - npm-debug.log
