source "https://rubygems.org"

gem "jekyll", "4.2.2"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Plugins
gem "jekyll-pandoc", group: :jekyll_plugins

# Plugins only for production
gem "jekyll-sitemap"
gem "jekyll-tidy"

# For Deployment
gem 's3_website'

# For Travis
gem 'html-proofer'
